### PR TITLE
Fix incorrect controlled `ConjugationBox` handling

### LINKED ISSUE #1109: Circuit with Controlled-`PauliExpBox` fails to compile for `AerBackend`
This circuit with controlled `PauliExpBox` fails to compile for `AerBackend`. 

circuit

The issue is fixed by downgrading the pytket version  from `1.21.0` to `1.20.1`.

I think something is going wrong with treating a controlled `PauliExpBox` as a `ConjugationBox` a feature which was added in 1.21.

[circuit.json](https://github.com/CQCL/tket/files/13282976/circuit.json)
```python
import json
from pytket import Circuit
from pytket.extensions.qiskit import AerBackend

with open('circuit.json', 'r', encoding='utf-8') as handle:
    circuit_dict = json.load(handle)
    
circ = Circuit.from_dict(circuit_dict)

backend  = AerBackend()
compiled = backend.get_compiled_circuit(circ)
```
With pytket 1.21.0 and pytket-qiskit 0.45 this gives the error

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [3], line 7
      1 from pytket.extensions.qiskit import AerBackend
      3 b = AerBackend()
----> 7 compiled = b.get_compiled_circuit(circ, optimisation_level=0)

File ~/.pyenv/versions/3.10.6/lib/python3.10/site-packages/pytket/backends/backend.py:183, in Backend.get_compiled_circuit(self, circuit, optimisation_level)
    178 """
    179 Return a single circuit compiled with :py:meth:`default_compilation_pass`. See
    180 :py:meth:`Backend.get_compiled_circuits`.
    181 """
    182 return_circuit = circuit.copy()
--> 183 self.default_compilation_pass(optimisation_level).apply(return_circuit)
    184 return return_circuit

RuntimeError: Circuit does not contain unit with id: q[3]
```

### PR DESCRIPTION
**Pull request by yao-cqc**
Fixes #1109

### CODE REVIEW

File: libs/tktokenswap/test/src/TableLookup/PermutationTestUtils.cpp [hunk 1]
```diff
@@ -14,8 +14,8 @@
 
 #include "PermutationTestUtils.hpp"
 
-#include <catch2/catch_test_macros.hpp>
```
Comment (cqc-alec) [inline libs/tktokenswap/test/src/TableLookup/PermutationTestUtils.cpp:17]: Should probably merge #1113 first (have added you as reviewer).

**Review by cqc-alec — COMMENTED** [review]
LGTM, once rebased on `develop`. Thanks!

**Review by cqc-alec — CHANGES_REQUESTED** [review]
Should bump tket library version in 2 conanfiles too (not detected in PR because of recency of last push)...

**Review by cqc-alec — APPROVED** [review]
