### PR TITLE
Don't reuse "stale" Pauli stabilizers when generating Pauli graphs

### LINKED ISSUE #1244: `PauliExponentials` pass changes circuit semantics
```python
from pytket.passes import PauliExponentials
from pytket.transform import PauliSynthStrat
from pytket import Circuit
from pytket.extensions.qiskit import AerBackend

import json

f = open("lcu_swap_circ.json")
data = json.load(f)
circ = Circuit.from_dict(data)

circ0 = circ.copy()
circ0.name = "original"

backend = AerBackend()

PauliExponentials(PauliSynthStrat.Individual).apply(circ)
compiled_circ = backend.get_compiled_circuit(circ, optimisation_level=0)
compiled_circ.name = "compiled"

expected = frozenset(
    [(0, 1, 0, 0, 0), (0, 1, 0, 1, 1), (0, 0, 0, 0, 0), (0, 0, 0, 1, 1)]
)

for c in [circ0, compiled_circ]:
    print(c.name)
    result = backend.run_circuit(c, n_shots=100)
    counts = result.get_counts()
    if any(tuple(res[-5:]) not in expected for res in counts.keys()):
        print("Unexpected result!")
    else:
        print("OK!")
```

Output:

```
original
OK!
compiled
Unexpected result!
```

[lcu_swap_circ.json](https://github.com/CQCL/tket/files/14208988/lcu_swap_circ.json)

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

Fixes a bug in applying `PhasedX` gates as sequences of `Rz` and `Rx` gates.

# Related issues

Fixes #1244 .

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have updated the changelog with any user-facing changes.

### CODE REVIEW

File: tket/test/src/test_CompilerPass.cpp [hunk 1]
```diff
@@ -2026,5 +2026,17 @@ SCENARIO(
     REQUIRE(cu.get_circ_ref().n_gates() == 1);
   }
 }
+
+SCENARIO("PauliExponentials") {
+  GIVEN("A PhasedX gate") {
+    // https://github.com/CQCL/tket/issues/1244
+    Circuit c(1);
+    c.add_op<unsigned>(OpType::PhasedX, {0.5, 0.6}, {0});
```
Comment (willsimmons1465) [inline tket/test/src/test_CompilerPass.cpp:2034]: Just for completeness, we could add another gate to test for a Clifford angle of beta (just switch the angles). Otherwise this all looks good to me!
