### PR TITLE
Fix implementations of symbol_substitution() for boxes that cannot contain symbols.

### LINKED ISSUE #999: Segfault substituting symbols in circuit containing boxes
Running

```python
import pickle
from pytket.circuit import Circuit

with open("my_circ.pickle", "rb") as f:
    cdict = pickle.load(f)
c = Circuit.from_dict(cdict)
sym_map = {s: 0.2 for s in c.free_symbols()}
c.symbol_substitution(sym_map)
```

with the attached file (unzipped) gives a segmentation fault.

[my_circ.zip](https://github.com/CQCL/tket/files/12512442/my_circ.zip)

### PR DESCRIPTION
**Pull request by cqc-alec**
These were just returning a null `Op_ptr`.

Fixes #999 .

### CODE REVIEW

File: tket/include/tket/Circuit/ConjugationBox.hpp [hunk 1]
```diff
@@ -47,7 +47,7 @@ class ConjugationBox : public Box {
 
   Op_ptr symbol_substitution(
       const SymEngine::map_basic_basic &) const override {
-    return Op_ptr();
+    return std::make_shared<ConjugationBox>(compute_, action_, uncompute_);
   }
```
Comment (yao-cqc) [inline tket/include/tket/Circuit/ConjugationBox.hpp:51]: `ConjugationBox` should support symbols, but we can fix it in a separate PR

**Review by yao-cqc — COMMENTED** [review]
Is there a reason not to call the copy constructors?
e.g. `return std::make_shared<Unitary1qBox>(*this);`

File: tket/include/tket/Circuit/ConjugationBox.hpp (hunk 1 above)
Comment (cqc-alec) [reply tket/include/tket/Circuit/ConjugationBox.hpp]: Made an issue and added a comment.
