### PR TITLE
Fix subcircuit finding algorithm

### LINKED ISSUE #1279: Occasional proptest failures relating to `gen_clifford_resynthesis_pass()`
E.g. https://github.com/CQCL/tket/actions/runs/8232300297/job/22509445073?pr=1278

### PR DESCRIPTION
**Pull request by cqc-alec**
# Description

The failures were due to the fact that we were implicitly identifying the vertices of the graph constructed by `boost::transitive_closure()` with the vertices of the original graph. I tried to fix this by providing an associative map; but for some reason the resulting generated graph was always the complete graph on all vertices. In the end I implemented transitive closure myself, which we can do fairly efficiently for DAGs if we start with a topological sort.

# Related issues

Fixes #1279 .

# Checklist

- [x] I have performed a self-review of my code.
- [x] I have commented hard-to-understand parts of my code.
- [ ] I have made corresponding changes to the public API documentation.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have updated the changelog with any user-facing changes.

### CODE REVIEW

File: tket/src/Circuit/SubcircuitFinder.cpp [hunk 1]
```diff
@@ -98,18 +98,38 @@ static subcircuit_info_t convex_union(
   return {verts, preds, succs};
 }
 
+static std::set<std::pair<Vertex, Vertex>> order_relations(
+    Circuit *circ /*const*/) {
```
Comment (cqc-alec) [inline tket/src/Circuit/SubcircuitFinder.cpp:102]: "Morally" `const`, but cannot be `const` because `index_vertices()` is not.

**Review by yao-cqc — APPROVED** [review]
Looks good
