### PR TITLE
Don't assume expressions being substituted are mod 4

### LINKED ISSUE #219: Symbol substitution converts symbols that are a multiple of 4 to zero
This was a hasty workaround for a symengine issue: https://github.com/CQCL/tket/blob/87a4effbf4f81d444c37540638c7b7b9f7e2e13e/tket/src/Circuit/Circuit.cpp#L142 .
However it leads to incorrect results if the symbol is part of a larger expression.

### PR DESCRIPTION
**Pull request by cqc-alec**
Fixes #219 .

### CODE REVIEW

File: tket/src/Circuit/Circuit.cpp [hunk 1]
```diff
@@ -142,7 +142,7 @@ void Circuit::symbol_substitution(const symbol_map_t &symbol_map) {
     // This is a workaround for a symengine issue: symengine currently has poor
     // handling of symbolic evaluations for atan2. However, this may not catch
     // every such issue, so we should revisit it.
```
Comment (ss2165) [inline tket/src/Circuit/Circuit.cpp:144]: is this comment still true?

**Review by ss2165 — APPROVED** [review]

File: tket/src/Circuit/Circuit.cpp (hunk 1 above)
Comment (cqc-alec) [reply tket/src/Circuit/Circuit.cpp:144]: Yes I think it is still true.
